# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-17 22:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehealth', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='folder',
            name='pages',
        ),
        migrations.AddField(
            model_name='page',
            name='folders',
            field=models.ManyToManyField(through='ehealth.FolderPage', to='ehealth.Folder'),
        ),
    ]
