# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-20 17:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehealth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='readability_score',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='page',
            name='sentiment_score',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='page',
            name='subjectivity_score',
            field=models.FloatField(default=0),
        ),
    ]
