# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-20 19:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehealth', '0002_auto_20160320_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='readability_score',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='page',
            name='sentiment_score',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='page',
            name='subjectivity_score',
            field=models.FloatField(default=1),
        ),
    ]
