# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-16 20:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehealth', '0002_auto_20160314_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searcher',
            name='picture',
            field=models.FileField(blank=True, upload_to=b'profile_images'),
        ),
    ]
