# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-13 17:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ehealth', '0002_auto_20160312_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='pages',
            field=models.ManyToManyField(blank=True, to='ehealth.Page'),
        ),
        migrations.AlterField(
            model_name='searcher',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
