# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-17 23:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehealth', '0003_auto_20160317_2302'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='folders',
        ),
        migrations.AddField(
            model_name='folder',
            name='pages',
            field=models.ManyToManyField(through='ehealth.FolderPage', to='ehealth.Page'),
        ),
    ]
