# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-21 01:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ehealth', '0004_auto_20160320_1938'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagecategory',
            name='category',
        ),
        migrations.RemoveField(
            model_name='pagecategory',
            name='page',
        ),
        migrations.RemoveField(
            model_name='query',
            name='category',
        ),
        migrations.RemoveField(
            model_name='querycategory',
            name='category',
        ),
        migrations.RemoveField(
            model_name='querycategory',
            name='query',
        ),
        migrations.RemoveField(
            model_name='userhistory',
            name='query',
        ),
        migrations.RemoveField(
            model_name='userhistory',
            name='user',
        ),
        migrations.RemoveField(
            model_name='page',
            name='category',
        ),
        migrations.RemoveField(
            model_name='searcher',
            name='history',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='PageCategory',
        ),
        migrations.DeleteModel(
            name='Query',
        ),
        migrations.DeleteModel(
            name='QueryCategory',
        ),
        migrations.DeleteModel(
            name='UserHistory',
        ),
    ]
