# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-18 00:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehealth', '0004_auto_20160317_2311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='pages',
            field=models.ManyToManyField(related_name='folders', through='ehealth.FolderPage', to='ehealth.Page'),
        ),
    ]
